name: Patch APK with ReVanced

on:
  workflow_dispatch:
  #schedule:
    #- cron: "0 12 * * *"  # daily at noon UTC

jobs:
  patch-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Download ReVanced CLI
        run: |
          curl -L -o revanced-cli.jar https://github.com/ReVanced/revanced-cli/releases/latest/download/revanced-cli.jar
          curl -L -o revanced-patches.jar https://github.com/ReVanced/revanced-patches/releases/latest/download/revanced-patches.jar
          curl -L -o revanced-integrations.apk https://github.com/ReVanced/revanced-integrations/releases/latest/download/app-release.apk

      - name: Download base APK (YouTube as example)
        run: |
          mkdir -p apks
          curl -L -o apks/youtube.apk "https://example.com/youtube.apk" # Replace with actual source

      - name: Patch APK
        run: |
          java -jar revanced-cli.jar \
            patch \
            -b revanced-patches.jar \
            -m revanced-integrations.apk \
            -o youtube-patched.apk \
            apks/youtube.apk

      - name: Upload as release asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "revanced-$(date +%Y%m%d)"
          files: youtube-patched.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
